Why numpy instead of lists ?


Lists are slow, while numpy is fast.<br>
In numpy it represents a data in an efficient memory manner. <br>
Faster to read less bytes of memory.<br>
It uses Contiguous memory. <br> 
while lists uses scattered computer's memory.<br>
SIMD Vector Processing<Br>
Effective Cache Utitilization<br>
MATLAB Replacment (Scikit learn gives lot more.)<Br>
Plotting(Matplotlib)<br>
Backend(Pandas)<Br>
Machine Learning<br>

In [6]:
import numpy as np
a = np.array([1,2,3], dtype=np.int16)
print(a)

[1 2 3]


In [7]:
b = np.array([[1,2,3],[4,5,6]], dtype=np.int16)
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
a.ndim, b.ndim, a.shape, b.shape, a.size, b.size, a.dtype, b.dtype

(1, 2, (3,), (2, 3), 3, 6, dtype('int16'), dtype('int16'))

In [9]:
# get rows length
a.shape[0], b.shape[0]

(3, 2)

In [10]:
# Know the memory size of the array
a.nbytes, b.nbytes

(6, 12)

### Accessing, Modifying elements, rows, columns etc.

In [11]:
a = np.arange(1,10001, dtype=np.int16).reshape(100,100)

print(a[6,:])


a[:,:],a.nbytes

[601 602 603 604 605 606 607 608 609 610 611 612 613 614 615 616 617 618
 619 620 621 622 623 624 625 626 627 628 629 630 631 632 633 634 635 636
 637 638 639 640 641 642 643 644 645 646 647 648 649 650 651 652 653 654
 655 656 657 658 659 660 661 662 663 664 665 666 667 668 669 670 671 672
 673 674 675 676 677 678 679 680 681 682 683 684 685 686 687 688 689 690
 691 692 693 694 695 696 697 698 699 700]


(array([[    1,     2,     3, ...,    98,    99,   100],
        [  101,   102,   103, ...,   198,   199,   200],
        [  201,   202,   203, ...,   298,   299,   300],
        ...,
        [ 9701,  9702,  9703, ...,  9798,  9799,  9800],
        [ 9801,  9802,  9803, ...,  9898,  9899,  9900],
        [ 9901,  9902,  9903, ...,  9998,  9999, 10000]],
       shape=(100, 100), dtype=int16),
 20000)

In [16]:
c = np.zeros((3,4, 3,2), dtype=np.int8)
c

array([[[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]]], dtype=int8)

In [18]:
np.full((2,3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [20]:
np.full_like(a, 99)

array([[99, 99, 99, ..., 99, 99, 99],
       [99, 99, 99, ..., 99, 99, 99],
       [99, 99, 99, ..., 99, 99, 99],
       ...,
       [99, 99, 99, ..., 99, 99, 99],
       [99, 99, 99, ..., 99, 99, 99],
       [99, 99, 99, ..., 99, 99, 99]], shape=(100, 100), dtype=int16)

In [ ]:
np.random.rand(4,2,3)

array([[[0.88937997, 0.27165396, 0.67189798],
        [0.49723674, 0.05796884, 0.25062304]],

       [[0.77938883, 0.50434543, 0.69391878],
        [0.22609108, 0.82203743, 0.68550429]],

       [[0.57756819, 0.51612806, 0.48513687],
        [0.30181591, 0.70679737, 0.70406977]],

       [[0.37345969, 0.11014513, 0.06099602],
        [0.53963338, 0.33829544, 0.76890982]]])

In [28]:
np.random.randint(1,10, size=(10,10))

array([[8, 9, 4, 8, 2, 7, 4, 2, 5, 5],
       [2, 7, 2, 5, 4, 4, 6, 8, 9, 3],
       [6, 9, 1, 6, 8, 5, 2, 7, 7, 3],
       [8, 5, 3, 4, 6, 1, 2, 1, 7, 2],
       [7, 6, 2, 8, 3, 4, 4, 3, 6, 3],
       [7, 2, 1, 3, 5, 2, 9, 1, 8, 4],
       [1, 1, 8, 1, 3, 2, 1, 9, 8, 8],
       [2, 6, 7, 5, 6, 4, 9, 9, 3, 7],
       [9, 2, 8, 6, 5, 4, 6, 3, 3, 4],
       [5, 6, 6, 2, 3, 7, 7, 9, 3, 6]])

In [29]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Important Methods

#### Copy Array

In [35]:
a = np.random.randint(1, 11, size=(3,5))

b = a
a[1][1] = 35
a,b

(array([[ 4,  5,  4,  5,  1],
        [ 2, 35,  3,  2,  1],
        [ 7,  8,  8,  9,  6]]),
 array([[ 4,  5,  4,  5,  1],
        [ 2, 35,  3,  2,  1],
        [ 7,  8,  8,  9,  6]]))

In [36]:
a = np.random.randint(1,11, size=(3,5))
b = a.copy()
a[1][1] = 35
b[1][1] = 98
a,b

(array([[ 2,  5,  5,  1,  4],
        [ 1, 35,  6,  3,  5],
        [ 3,  5,  1,  2, 10]]),
 array([[ 2,  5,  5,  1,  4],
        [ 1, 98,  6,  3,  5],
        [ 3,  5,  1,  2, 10]]))