Why numpy instead of lists ?


Lists are slow, while numpy is fast.<br>
In numpy it represents a data in an efficient memory manner. <br>
Faster to read less bytes of memory.<br>
It uses Contiguous memory. <br> 
while lists uses scattered computer's memory.<br>
SIMD Vector Processing<Br>
Effective Cache Utitilization<br>
MATLAB Replacment (Scikit learn gives lot more.)<Br>
Plotting(Matplotlib)<br>
Backend(Pandas)<Br>
Machine Learning<br>

In [3]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
a.ndim

1

In [7]:
b.shape

(2, 3)

In [12]:
b[0,:]

array([1, 2, 3])